apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k8sdemo-def1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k8sdemo-def1"
  template:
    metadata:
      labels:
        app: "k8sdemo-def1"
    spec:
      containers:
        - name: "k8sdemo-def1"
          image: "azuso.azurecr.io/k8sdemo"
          ports:
          - containerPort: 80