on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: azuso.azurecr.io
        username: ${{ secrets.acr_azuso_username }}
        password: ${{ secrets.acr_azuso_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t azuso.azurecr.io/k8sdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push azuso.azurecr.io/k8sdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8sdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8s-demoa8a0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8s-demoa8a0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8s-demoa8a0
        container-registry-url: azuso.azurecr.io
        container-registry-username: ${{ secrets.acr_azuso_username }}
        container-registry-password: ${{ secrets.acr_azuso_password }}
        secret-name: k8sdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8s-demoa8a0
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          azuso.azurecr.io/k8sdemo:${{ github.sha }}
        imagepullsecrets: |
          k8sdemodockerauth
